/*
 * Copyright (c) 2011 Topmedia Company
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package vn.topmedia.monitor.form;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import vn.topmedia.monitor.MonitorBean;

/**
 *
 * @author Anh Tuan <tuanta@topmedia.vn>
 */
public class Messaging extends javax.swing.JDialog {

    /**
     * Creates new form Messaging
     */
    public Messaging(MDIMain parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mdiMain = parent;
        inits();
    }

    public Messaging(MDIMain parent, boolean modal, String type) {
        super(parent, modal);
        initComponents();
        this.mdiMain = parent;
        txtInfo.setText(type);
        lblCharCount.setText(String.valueOf(type.length()));
        pack();
        inits();
    }

    public Messaging(MDIMain parent, boolean modal, MonitorBean bean) {
        super(parent, modal);
        initComponents();
        this.mdiMain = parent;
        txtInfo.setText(bean.getInfo());
        lblCharCount.setText(String.valueOf(bean.getInfo().length()));
        inits();
    }

    private void inits() {
        Dimension d = mdiMain.getSize();
        this.setLocation((d.width - this.getWidth()) / 2, (d.height - this.getHeight()) / 3);
        pnlMessaging.registerKeyboardAction(new ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent actionEvent) {
            }
        }, KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0, false),
                JPanel.WHEN_IN_FOCUSED_WINDOW);

        pnlMessaging.registerKeyboardAction(new ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent actionEvent) {
                btnCloseActionPerformed(actionEvent);
            }
        }, KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0, false),
                JPanel.WHEN_IN_FOCUSED_WINDOW);

//        if (mdiMain.getYM() == null) {
//            txtYID.setEnabled(false);
//        }
//        if (Constants.DBA_USERS.indexOf(mdiMain.getUserName()) < 0) {
//            btnPushMT.setVisible(false);
//            lblCommandCode.setVisible(false);
//            txtCommandCode.setVisible(false);
//        }
//        DefaultComboBoxModel defaultModel = new DefaultComboBoxModel(MDIMain.getMonCPs());
//        cmbServiceID.setModel(defaultModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMessaging = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        lblInfo = new javax.swing.JLabel();
        lblCharCount = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Send Message");
        setModal(true);
        setResizable(false);

        txtInfo.setColumns(20);
        txtInfo.setLineWrap(true);
        txtInfo.setRows(5);
        txtInfo.setWrapStyleWord(true);
        txtInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInfoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtInfo);

        lblInfo.setText("Info:");

        lblCharCount.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblCharCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCharCount.setText("0");
        lblCharCount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlMessagingLayout = new org.jdesktop.layout.GroupLayout(pnlMessaging);
        pnlMessaging.setLayout(pnlMessagingLayout);
        pnlMessagingLayout.setHorizontalGroup(
            pnlMessagingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlMessagingLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblInfo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlMessagingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlMessagingLayout.createSequentialGroup()
                        .add(lblCharCount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnClose))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMessagingLayout.setVerticalGroup(
            pnlMessagingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlMessagingLayout.createSequentialGroup()
                .add(pnlMessagingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlMessagingLayout.createSequentialGroup()
                        .add(68, 68, 68)
                        .add(lblInfo))
                    .add(pnlMessagingLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlMessagingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btnClose)
                    .add(lblCharCount)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlMessaging, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(pnlMessaging, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInfoKeyReleased
        // TODO add your handling code here:
        lblCharCount.setText(String.valueOf(txtInfo.getText().length()));
    }//GEN-LAST:event_txtInfoKeyReleased

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCharCount;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JPanel pnlMessaging;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
    private MDIMain mdiMain;
}
